import json
import os

from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/fairness", tags=["fairness"])

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # -> backend/
REPORT_PATH = os.path.join(BASE_DIR, "models", "fairness_report.json")


@router.get("/report")
def fairness_report():
    """Returns the statistical fairness report (Section 4.3 bonus feature) —
    approval-rate parity + disparate-impact-ratio across demographic groups.
    Generated by training/fairness_check.py; regenerate that after retraining."""
    if not os.path.exists(REPORT_PATH):
        raise HTTPException(
            status_code=404,
            detail="Fairness report not found. Run training/fairness_check.py first.",
        )
    with open(REPORT_PATH) as f:
        return json.load(f)
